language: ruby

rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx
  - ruby-head
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - gem update --system
  - gem --version

branches:
  only:
    - master